version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sofia_health
      - POSTGRES_USER=sofia_user
      - POSTGRES_PASSWORD=sofia_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sofia_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: gunicorn sofia_health.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-only-for-local-development
      - DATABASE_URL=postgresql://sofia_user:sofia_pass@db:5432/sofia_health
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-your_stripe_test_publishable_key}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-your_stripe_test_secret_key}
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0

volumes:
  postgres_data: